# Sequence save poses

Save a list of poses for an entire sequence for use with full Bundle Adjustment

In [1]:
# when you change a setting you have to restart the kernel (settings are only loaded once)
import os
os.environ['STEREO_CONFIDENCE'] = '1.6'
os.environ['SEQUENCE_CONFIDENCE'] = '1.6'
#os.environ['PATCH_SIZE'] = '17'
FRAMECOUNT = 1101

import sys
sys.path.append('..')
from src.kitti import *
%matplotlib inline
import numpy as np
import glob

Read the first 10 frames from KITTI sequence 00.

In [ ]:
%%time
LEFTDIR = '/data/urbinn/datasets/kitti/sequences/01/image_2'
RIGHTDIR = '/data/urbinn/datasets/kitti/sequences/01/image_3'

frame = []
for filename in sorted(glob.glob(LEFTDIR + '/*')):
    left_frame = Frame(filename, RIGHTDIR)
    frame.append(left_frame)

CPU times: user 6.38 ms, sys: 0 ns, total: 6.38 ms
Wall time: 5.12 ms


Inspect the FramePoints for the first frame

We can also manually compute the Depth of the points and show these

Turn the list of frames into a sequence. The first frame is automatically taken as the KeyFrame and its FramePoints are rerieved, depth is estimated, only the most confident points are kept, and they are tracked in the other frames.

In [ ]:
seq = Sequence()
for f in ProgressBar()(frame[:]):
    seq.add_frame(f)

N/A% (0 of 1101) |                       | Elapsed Time: 0:00:00 ETA:  --:--:--

set_previous_keyframe 0


  0% (1 of 1101) |                        | Elapsed Time: 0:00:04 ETA:  1:18:29

get_world_pose first  0


  0% (3 of 1101) |                        | Elapsed Time: 0:00:07 ETA:  0:43:29

invalid speed keyframe 0 frame 3 speed 0.08575096510280411
 [[ 0.99285792  0.00306889 -0.1192633  -0.68171559]
 [-0.00233101  0.99997727  0.00632595  0.22051717]
 [ 0.11928001 -0.00600277  0.99284251 -1.51089768]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 2
get_world_pose  2 [[ 0.99431572  0.00845802 -0.10613538  1.52357686]
 [-0.00725107  0.99990465  0.01175249 -0.36723402]
 [ 0.10622466 -0.01091609  0.99428223 -1.59664865]
 [ 0.          0.          0.          1.        ]]


  0% (5 of 1101) |                        | Elapsed Time: 0:00:15 ETA:  0:56:27

set_previous_keyframe 4
get_world_pose  4 [[  9.77807919e-01   3.79459203e-03  -2.09469028e-01   3.06587507e+00]
 [  5.56194860e-04   9.99785417e-01   2.07077369e-02  -5.81284086e-01]
 [  2.09502657e-01  -2.03646947e-02   9.77595988e-01  -2.92247596e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  0% (7 of 1101) |                        | Elapsed Time: 0:00:24 ETA:  1:02:36

set_previous_keyframe 6
get_world_pose  6 [[  9.57549224e-01   1.07975069e-02  -2.88067522e-01   2.18862590e+00]
 [ -5.17646152e-03   9.99781191e-01   2.02675664e-02  -3.65073375e-01]
 [  2.88223330e-01  -1.79160220e-02   9.57395597e-01  -5.56347273e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  0% (8 of 1101) |                        | Elapsed Time: 0:00:30 ETA:  1:08:43

invalid speed keyframe 6 frame 8 speed 0.7253782859590414
 [[ 0.99571801  0.00845601 -0.09205507  0.47384455]
 [-0.0081295   0.99995927  0.0039213   0.03094385]
 [ 0.09208448 -0.00315615  0.9957462  -0.12882137]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 7
get_world_pose  7 [[ 0.94172696  0.01636344 -0.33598001  2.68021548]
 [-0.0090852   0.99968902  0.02322332 -0.28798823]
 [ 0.33625554 -0.01881758  0.94158277 -6.25943182]
 [ 0.          0.          0.          1.        ]]


  0% (9 of 1101) |                        | Elapsed Time: 0:00:35 ETA:  1:12:24

7 8 286 0.187212503036 0.088555726649 [[ 0.99606078  0.00456141 -0.08855573  0.61011937]
 [-0.00443073  0.99998879  0.00167221  0.07022433]
 [ 0.08856236 -0.00127325  0.99606982  0.1872125 ]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 8
get_world_pose  8 [[ 0.94124017  0.01758959 -0.33727962  2.87423472]
 [-0.01018026  0.99966671  0.02372408 -0.25402758]
 [ 0.3375845  -0.01889646  0.94110554 -6.15791798]
 [ 0.          0.          0.          1.        ]]


  0% (10 of 1101) |                       | Elapsed Time: 0:00:41 ETA:  1:14:36

8 9 285 2.89586971763 0.0668533734852 [[  9.97762675e-01  -5.19863631e-04  -6.68533735e-02  -2.68526996e-01]
 [ -4.15187230e-04   9.99902302e-01  -1.39719376e-02   5.71913655e-01]
 [  6.68541055e-02   1.39684345e-02   9.97664980e-01   2.89586972e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  0% (11 of 1101) |                       | Elapsed Time: 0:00:42 ETA:  1:08:38

set_previous_keyframe 10
get_world_pose  10 [[  9.01904518e-01   1.09961322e-02  -4.31795467e-01   3.70282505e+00]
 [  8.04634226e-04   9.99631391e-01   2.71373440e-02  -4.05781564e-01]
 [  4.31934709e-01  -2.48227306e-02   9.01563220e-01  -8.14085679e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (12 of 1101) |                       | Elapsed Time: 0:00:46 ETA:  1:13:52

set_previous_keyframe 11
get_world_pose  11 [[ 0.87335836  0.02544634 -0.48641306  4.8116768 ]
 [-0.0119744   0.99945428  0.03078559 -0.36214493]
 [ 0.48693099 -0.02106235  0.87318646 -8.91395346]
 [ 0.          0.          0.          1.        ]]


  1% (14 of 1101) |                       | Elapsed Time: 0:00:50 ETA:  1:07:00

invalid speed keyframe 11 frame 14 speed 4.893344698994428
 [[ 0.98320538  0.02256011 -0.18110282 -0.42167759]
 [-0.02261244  0.99974273  0.00177598  0.32443743]
 [ 0.18109629  0.00234902  0.98346256  1.6828608 ]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 13
get_world_pose  13 [[  7.95685119e-01   2.46012453e-02  -6.05210682e-01   6.49094104e+00]
 [ -5.92094277e-03   9.99443017e-01   3.28420124e-02  -3.80297680e-01]
 [  6.05681544e-01  -2.25484828e-02   7.95387599e-01  -1.11901163e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (15 of 1101) |                       | Elapsed Time: 0:00:54 ETA:  1:09:57

set_previous_keyframe 14
get_world_pose  14 [[  0.77280721   0.02396702  -0.63418814   6.83720316]
 [ -0.01078768   0.99963837   0.02463238   0.08851077]
 [  0.63454917  -0.01219466   0.77278629 -10.53806434]
 [  0.           0.           0.           1.        ]]


  1% (16 of 1101) |                       | Elapsed Time: 0:00:57 ETA:  1:02:34

set_previous_keyframe 15
get_world_pose  15 [[  7.10851593e-01   2.34618077e-02  -7.02950607e-01   7.32708579e+00]
 [ -9.56486813e-03   9.99673526e-01   2.36929111e-02   1.44838169e-01]
 [  7.03276991e-01  -1.01185138e-02   7.10843928e-01  -1.04431125e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (17 of 1101) |                       | Elapsed Time: 0:01:00 ETA:  1:05:59

15 16 331 0.403590911243 0.123491275937 [[ 0.99211073 -0.02159196 -0.12349128  0.98437037]
 [ 0.02198246  0.99975674  0.0018004   0.08807932]
 [ 0.12342236 -0.00450084  0.99234402  0.40359091]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 16
get_world_pose  16 [[ 0.71539222  0.02422136 -0.69830316  7.83781943]
 [-0.01006769  0.99965256  0.02435989  0.0697894 ]
 [ 0.69865057 -0.01039658  0.71538752 -9.88109816]
 [ 0.          0.          0.          1.        ]]


  1% (18 of 1101) |                       | Elapsed Time: 0:01:04 ETA:  1:01:02

16 17 352 3.64846036882 0.129340968244 [[ 0.99145824 -0.01677734 -0.12934097  0.0366217 ]
 [ 0.01402778  0.99965646 -0.02214003  0.75007117]
 [ 0.12966799  0.02013654  0.99135298  3.64846037]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 17
get_world_pose  17 [[  7.17319328e-01   4.07515532e-02  -6.95551790e-01   7.26605325e+00]
 [ -2.50522334e-02   9.99151095e-01   3.27028241e-02   1.25216197e-01]
 [  6.96294023e-01  -6.03324202e-03   7.17731310e-01  -1.05767383e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (19 of 1101) |                       | Elapsed Time: 0:01:07 ETA:  0:56:23

set_previous_keyframe 18
get_world_pose  18 [[  0.63751837   0.03968076  -0.76941261   8.41094349]
 [ -0.01602314   0.99913965   0.038252    -0.05431313]
 [  0.77026851  -0.01205794   0.6376057  -11.82833187]
 [  0.           0.           0.           1.        ]]


  1% (20 of 1101) |                       | Elapsed Time: 0:01:10 ETA:  0:52:34

18 19 314 3.5759640185 0.0964165593802 [[ 0.99522164  0.01541849 -0.09641656  0.2104028 ]
 [-0.0177715   0.99956366 -0.02359369  0.89050343]
 [ 0.09601071  0.02519442  0.9950614   3.57596402]
 [ 0.          0.          0.          1.        ]]
invalid speed keyframe 18 frame 20 speed 4.819580994123748
 [[ 0.99075734  0.03417546 -0.13127046 -1.47864991]
 [-0.02725063  0.99815863  0.05419174 -4.58674553]
 [ 0.13288077 -0.05011366  0.9898643   4.81958099]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 19
get_world_pose  19 [[  6.43543163e-01   2.92713942e-02  -7.64849909e-01   8.21734229e+00]
 [ -1.28198297e-02   9.99540513e-01   2.74666054e-02   2.60065676e-01]
 [  7.65302456e-01  -7.87070053e-03   6.43622718e-01  -1.08628318e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (21 of 1101) |                       | Elapsed Time: 0:01:13 ETA:  0:56:32

19 20 373 3.33073506598 0.097338090322 [[ 0.99523708  0.00533372 -0.09733809 -0.13584618]
 [-0.00689202  0.99985331 -0.01567991  0.51532756]
 [ 0.09724018  0.01627609  0.99512785  3.33073507]
 [ 0.          0.          0.          1.        ]]
invalid speed keyframe 19 frame 21 speed 5.99932510592264
 [[ 0.98429071 -0.01802888 -0.17563244  1.09293958]
 [ 0.01394755  0.99960388 -0.02444479  0.89560573]
 [ 0.17600358  0.02161114  0.98415227  5.99932511]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 20
get_world_pose  20 [[  6.33239447e-01   3.43250266e-02  -7.73194410e-01   8.02024582e+00]
 [ -1.55311381e-02   9.99378454e-01   3.16463264e-02   8.28319639e-02]
 [  7.73800095e-01  -8.03111310e-03   6.33378966e-01  -1.06211358e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (22 of 1101) |                       | Elapsed Time: 0:01:16 ETA:  0:54:40

20 21 325 0.922820773126 0.0833294392683 [[ 0.99641122  0.014862   -0.08332944  0.25551291]
 [-0.01467947  0.99988832  0.00280279  0.10938702]
 [ 0.08336179 -0.00156949  0.99651811  0.92282077]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 21
get_world_pose  21 [[  6.12703158e-01   2.81218507e-02  -7.89812637e-01   8.54354171e+00]
 [ -1.21345854e-02   9.99583661e-01   2.61774030e-02   2.83258732e-01]
 [  7.90219965e-01  -6.45492858e-03   6.12789312e-01  -1.05243565e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (23 of 1101) |                       | Elapsed Time: 0:01:20 ETA:  0:53:56

21 22 336 2.0965246847 0.0891739589412 [[ 0.9959966  -0.00622767 -0.08917396  0.03913785]
 [ 0.00600482  0.99997814 -0.00276717  0.41259975]
 [ 0.08918924  0.00222061  0.99601222  2.09652468]
 [ 0.          0.          0.          1.        ]]


  2% (25 of 1101) |                       | Elapsed Time: 0:01:21 ETA:  0:49:13

set_previous_keyframe 24
get_world_pose  24 [[  4.55074795e-01   4.96378552e-02  -8.89068622e-01   1.11093544e+01]
 [ -1.54921891e-02   9.98735298e-01   4.78309236e-02   9.27547587e-02]
 [  8.90318439e-01  -7.99302851e-03   4.55268260e-01  -1.38470399e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (27 of 1101) |                       | Elapsed Time: 0:01:25 ETA:  0:45:01

invalid speed keyframe 24 frame 27 speed 4.3876357117541165
 [[ 0.99369072 -0.02594541 -0.10911269 -0.34446028]
 [ 0.02408968  0.99954245 -0.0182916   0.44485359]
 [ 0.10953735  0.0155477   0.99386108  2.27703075]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 26
get_world_pose  26 [[  3.86995603e-01   5.11048821e-02  -9.20664268e-01   1.24918923e+01]
 [ -1.29969357e-02   9.98666076e-01   4.99714789e-02   2.04819896e-01]
 [  9.21989958e-01  -7.37292829e-03   3.87143587e-01  -1.35432813e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (28 of 1101) |                       | Elapsed Time: 0:01:29 ETA:  0:45:36

invalid speed keyframe 26 frame 28 speed 0.5832972456022074
 [[ 0.99441911  0.00277876 -0.10546524  1.35723101]
 [-0.0031363   0.99998988 -0.0032244  -0.09511686]
 [ 0.10545522  0.00353718  0.99441776 -0.45238719]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 27
get_world_pose  27 [[  3.52394980e-01   5.39412040e-02  -9.34295523e-01   1.30194615e+01]
 [ -9.34357756e-03   9.98490544e-01   5.41232951e-02   1.57927461e-02]
 [  9.35804721e-01  -1.03431148e-02   3.52367059e-01  -1.46899587e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (29 of 1101) |                       | Elapsed Time: 0:01:34 ETA:  0:48:11

set_previous_keyframe 28
get_world_pose  28 [[  3.01725671e-01   5.59644358e-02  -9.51750808e-01   1.37742599e+01]
 [ -4.93684864e-03   9.98353987e-01   5.71396874e-02  -8.48453191e-02]
 [  9.53382005e-01  -1.25418608e-02   3.01505315e-01  -1.42934938e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (30 of 1101) |                       | Elapsed Time: 0:01:39 ETA:  0:51:45

28 29 324 0.630563290665 0.0519716737878 [[ 0.99864763  0.00136137 -0.05197167  0.17897804]
 [-0.00198303  0.99992708 -0.01191192  0.35174666]
 [ 0.05195167  0.01199888  0.99857751  0.63056329]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 29
get_world_pose  29 [[  3.05694020e-01   4.44513116e-02  -9.51091608e-01   1.37913360e+01]
 [ -9.08756445e-03   9.99000321e-01   4.37695592e-02   2.35194212e-01]
 [  9.52086436e-01  -4.73698623e-03   3.05792378e-01  -1.34580048e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (31 of 1101) |                       | Elapsed Time: 0:01:45 ETA:  0:56:42

set_previous_keyframe 30
get_world_pose  30 [[  2.47957773e-01   5.43967815e-02  -9.67242437e-01   1.35989042e+01]
 [ -6.38366541e-03   9.98492395e-01   5.45177621e-02   4.74493362e-01]
 [  9.68749809e-01  -7.34355081e-03   2.47931202e-01  -1.39959358e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (32 of 1101) |                       | Elapsed Time: 0:01:52 ETA:  1:03:18

invalid speed keyframe 30 frame 32 speed 0.022920799178330675
 [[  9.95466967e-01   3.35540226e-04  -9.51073314e-02   1.27687505e+00]
 [  2.12523623e-04   9.99983432e-01   5.75239474e-03  -1.65429005e-01]
 [  9.51076859e-02  -5.74653150e-03   9.95450403e-01  -1.04508569e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 31
get_world_pose  31 [[  2.21248772e-01   4.27355988e-02  -9.74280580e-01   1.47116807e+01]
 [ -4.18584040e-03   9.99071784e-01   4.28724740e-02   3.59421050e-01]
 [  9.75208419e-01  -5.40729922e-03   2.21222290e-01  -1.48754955e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (33 of 1101) |                       | Elapsed Time: 0:02:00 ETA:  1:11:05

invalid speed keyframe 31 frame 33 speed 1.5788086722723056
 [[ 0.99735674  0.00640519 -0.07237746  0.2927388 ]
 [-0.00705718  0.99993676 -0.00875604  0.30723682]
 [ 0.0723168   0.00924367  0.99733888  1.15045014]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 32
get_world_pose  32 [[  1.78746295e-01   4.19310225e-02  -9.83001298e-01   1.51123531e+01]
 [ -5.48916890e-03   9.99118418e-01   4.16203807e-02   5.09283831e-01]
 [  9.83879887e-01  -2.04362868e-03   1.78818882e-01  -1.49271736e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  3% (34 of 1101) |                       | Elapsed Time: 0:02:09 ETA:  1:25:50

invalid speed keyframe 32 frame 34 speed 1.7013374614532006
 [[ 0.99485435 -0.01614725 -0.10002047  2.17645549]
 [ 0.01525001  0.99983638 -0.00972873  0.34557331]
 [ 0.1001612   0.00815335  0.99493782  1.26424404]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 33
get_world_pose  33 [[  1.39049610e-01   3.89760603e-02  -9.89518101e-01   1.55993985e+01]
 [ -6.61784365e-03   9.99239418e-01   3.84290163e-02   4.91256100e-01]
 [  9.90263303e-01   1.20493635e-03   1.39201789e-01  -1.51605843e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  3% (36 of 1101) |                       | Elapsed Time: 0:02:21 ETA:  1:41:00

invalid speed keyframe 33 frame 36 speed 2.5519473745132224
 [[ 0.99211419 -0.00696066 -0.12514383  2.00317475]
 [ 0.00584984  0.99994018 -0.00924164 -0.01029758]
 [ 0.12520067  0.00843669  0.99209557  1.71102564]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 35
get_world_pose  35 [[  5.78241896e-02   4.17351874e-02  -9.97454028e-01   1.64917944e+01]
 [ -5.64791004e-03   9.99123470e-01   4.14776203e-02   5.28266684e-01]
 [  9.98310805e-01   3.23512083e-03   5.80092216e-02  -1.52925542e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  3% (38 of 1101) |                       | Elapsed Time: 0:02:37 ETA:  1:59:49

invalid speed keyframe 35 frame 38 speed 3.0186120751831576
 [[ 0.9968726  -0.00392348 -0.07892792  0.67528538]
 [ 0.0037292   0.99998964 -0.00260867  0.14150968]
 [ 0.07893734  0.00230617  0.99687691  1.05953954]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 37
get_world_pose  37 [[  1.03106169e-02   3.73305894e-02  -9.99249778e-01   1.91434882e+01]
 [ -1.02140307e-02   9.99254695e-01   3.72253811e-02   3.27497792e-01]
 [  9.99894677e-01   9.82255128e-03   1.06842281e-02  -1.66052906e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  3% (39 of 1101) |                       | Elapsed Time: 0:02:50 ETA:  2:15:07

invalid speed keyframe 37 frame 39 speed 2.404496975659737
 [[  9.98890219e-01   1.33124023e-02  -4.51786396e-02   1.16428829e+00]
 [ -1.32678140e-02   9.99911151e-01   1.28666677e-03  -2.35820640e-01]
 [  4.51917541e-02  -6.85817066e-04   9.98978095e-01   1.27493886e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 38
get_world_pose  38 [[  9.98932706e-03   4.94672283e-02  -9.98725792e-01   1.84582449e+01]
 [ -9.61703844e-03   9.98734185e-01   4.93714537e-02   2.48803119e-01]
 [  9.99903858e-01   9.11159673e-03   1.04524107e-02  -1.76371916e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  3% (41 of 1101) |                       | Elapsed Time: 0:03:08 ETA:  2:26:16

invalid speed keyframe 38 frame 41 speed 3.11136688587403
 [[  9.97618497e-01   1.25660642e-02  -6.78190814e-02  -1.34247245e+00]
 [ -1.26074018e-02   9.99920507e-01  -1.81542110e-04  -8.92051733e-01]
 [  6.78114090e-02   1.03613218e-03   9.97697619e-01   2.45438168e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 40
get_world_pose  40 [[ -0.05341383   0.05182188  -0.99722688  18.47326284]
 [ -0.01893807   0.99842031   0.05289827  -0.10411849]
 [  0.99839286   0.02171105  -0.05234805 -16.98165739]
 [  0.           0.           0.           1.        ]]


  3% (43 of 1101) |                       | Elapsed Time: 0:03:27 ETA:  2:34:06

invalid speed keyframe 40 frame 43 speed 2.1698675551308115
 [[ 0.99578309 -0.02311595 -0.08877891  0.93940343]
 [ 0.0220236   0.99966946 -0.01326423  0.79017694]
 [ 0.08905618  0.01125306  0.99596303  0.69465067]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 42
get_world_pose  42 [[ -0.08968066   0.05352855  -0.99453108  20.74553166]
 [ -0.02241489   0.9981933    0.0557469    0.32660259]
 [  0.99571831   0.02729173  -0.08831879 -18.12948209]
 [  0.           0.           0.           1.        ]]


  4% (45 of 1101) |                       | Elapsed Time: 0:03:51 ETA:  2:41:52

set_previous_keyframe 44
get_world_pose  44 [[ -1.09490952e-01   6.91219382e-02  -9.91581509e-01   2.26553307e+01]
 [ -1.71825327e-02   9.97298483e-01   7.14177657e-02   1.34820230e-01]
 [  9.93839269e-01   2.48574808e-02  -1.08007471e-01  -1.94314840e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (46 of 1101) |                       | Elapsed Time: 0:04:13 ETA:  3:16:00

invalid speed keyframe 44 frame 46 speed 0.1695447436096662
 [[  9.99648371e-01   7.04632389e-04  -2.65073228e-02   7.28605905e-01]
 [ -5.46373531e-04   9.99981987e-01   5.97715160e-03  -1.37132521e-01]
 [  2.65110570e-02  -5.96056696e-03   9.99630750e-01  -1.05077885e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 45
get_world_pose  45 [[ -1.13364204e-01   7.30776099e-02  -9.90862362e-01   2.24018686e+01]
 [ -1.55161428e-02   9.97039566e-01   7.53083844e-02   2.00259135e-01]
 [  9.93432336e-01   2.39116370e-02  -1.11894714e-01  -2.10307268e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (48 of 1101) |#                      | Elapsed Time: 0:04:44 ETA:  3:43:23

invalid speed keyframe 45 frame 48 speed 6.449969365089936
 [[  9.99366225e-01  -2.36001392e-03  -3.55187204e-02  -7.75685739e-01]
 [  2.84450159e-03   9.99903524e-01   1.35960015e-02  -1.83156862e+00]
 [  3.54832070e-02  -1.36884178e-02   9.99276523e-01   4.13709295e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 47
get_world_pose  47 [[ -1.41410811e-01   8.02844141e-02  -9.86690121e-01   2.46141427e+01]
 [ -1.37938139e-02   9.96449461e-01   8.30554131e-02  -5.15944314e-02]
 [  9.89854895e-01   2.53551533e-02  -1.39801298e-01  -2.04116506e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (49 of 1101) |#                      | Elapsed Time: 0:05:11 ETA:  4:07:36

invalid speed keyframe 47 frame 49 speed 0.4260572437575564
 [[ 0.99984996 -0.0039369  -0.01686872  0.53157456]
 [ 0.00396159  0.99999113  0.00143039 -0.06927232]
 [ 0.01686294 -0.001497    0.99985669 -0.87007276]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 48
get_world_pose  48 [[ -1.48225099e-01   8.17485793e-02  -9.85569120e-01   2.57307497e+01]
 [ -1.08475828e-02   9.96383319e-01   8.42769960e-02  -1.95030083e-01]
 [  9.88894155e-01   2.31830088e-02  -1.46802242e-01  -2.03641820e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (50 of 1101) |#                      | Elapsed Time: 0:05:40 ETA:  4:32:58

invalid speed keyframe 48 frame 50 speed 0.8838270919745062
 [[  9.99804521e-01  -7.03293263e-03  -1.84785507e-02   3.59704680e-01]
 [  7.04584204e-03   9.99974977e-01   6.33603848e-04   6.10906534e-02]
 [  1.84736322e-02  -7.63676941e-04   9.99829056e-01  -4.33829784e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 49
get_world_pose  49 [[ -1.50070263e-01   8.18169092e-02  -9.85284177e-01   2.58267798e+01]
 [ -8.57992905e-03   9.96424698e-01   8.40488290e-02  -2.60991658e-01]
 [  9.88638104e-01   2.10668982e-02  -1.48831733e-01  -2.13659743e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (51 of 1101) |#                      | Elapsed Time: 0:06:10 ETA:  5:18:29

invalid speed keyframe 49 frame 51 speed -4.027570019972234
 [[ 0.99918198  0.04000281 -0.00592924  0.23117417]
 [-0.03995945  0.99917493  0.00725909 -0.44336877]
 [ 0.00621473 -0.00701622  0.99995607 -5.3588357 ]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 50
get_world_pose  50 [[ -1.54511479e-01   8.23815426e-02  -9.84550397e-01   2.65795767e+01]
 [ -8.61772507e-03   9.96367297e-01   8.47227451e-02  -3.29794973e-01]
 [  9.87953409e-01   2.15752213e-02  -1.53240243e-01  -2.16660147e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (52 of 1101) |#                      | Elapsed Time: 0:06:42 ETA:  5:48:11

invalid speed keyframe 50 frame 52 speed 9.119133129727086
 [[ 0.99285622  0.11379625  0.03587389 -2.64189825]
 [-0.11469726  0.99310713  0.02414065 -0.99355295]
 [-0.0328795  -0.02808283  0.99906471  7.77501912]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 51
get_world_pose  51 [[ -1.56204551e-01   8.25599208e-02  -9.84268255e-01   2.70062696e+01]
 [ -6.65576621e-03   9.96389965e-01   8.46329617e-02  -3.67916245e-01]
 [  9.87702303e-01   1.97711131e-02  -1.55091147e-01  -2.23943184e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (53 of 1101) |#                      | Elapsed Time: 0:07:15 ETA:  6:37:37

invalid speed keyframe 51 frame 53 speed 7.2360505298469295
 [[  9.99664827e-01  -2.55403032e-02  -4.23403008e-03  -2.16553216e+00]
 [  2.55008209e-02   9.99633104e-01  -9.13051122e-03   8.97947518e-01]
 [  4.46567265e-03   9.01947968e-03   9.99949352e-01   5.84785583e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 52
get_world_pose  52 [[ -1.58756250e-01   8.39939550e-02  -9.83738516e-01   2.75450760e+01]
 [ -6.37910212e-03   9.96266674e-01   8.60931020e-02  -4.76346175e-01]
 [  9.87297199e-01   1.99431865e-02  -1.57627755e-01  -2.30057158e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (54 of 1101) |#                      | Elapsed Time: 0:07:50 ETA:  7:07:32

invalid speed keyframe 52 frame 54 speed 2.7424973243461066
 [[ 0.99996046 -0.00769035 -0.00446553 -1.02224092]
 [ 0.00768126  0.9999684  -0.00204904 -0.50875303]
 [ 0.00448114  0.00201466  0.99998793  1.34216683]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 53
get_world_pose  53 [[ -1.58635055e-01   8.40973336e-02  -9.83749235e-01   2.77931176e+01]
 [ -5.42105367e-03   9.96276724e-01   8.60424406e-02  -5.19404780e-01]
 [  9.87322405e-01   1.89823047e-02  -1.57588517e-01  -2.38660421e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (55 of 1101) |#                      | Elapsed Time: 0:08:27 ETA:  8:00:41

invalid speed keyframe 53 frame 55 speed 3.5436133692760734
 [[ 0.99983865  0.01770159 -0.00305565 -0.34047614]
 [-0.0177244   0.99981397 -0.00760685  0.04741917]
 [ 0.00292043  0.00765978  0.9999664   2.15131185]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 54
get_world_pose  54 [[ -1.58202357e-01   8.32020046e-02  -9.83895035e-01   2.79707339e+01]
 [ -6.08974719e-03   9.96342370e-01   8.52337818e-02  -5.81200661e-01]
 [  9.87387933e-01   1.94758572e-02  -1.57117032e-01  -2.47658451e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (56 of 1101) |#                      | Elapsed Time: 0:09:04 ETA:  8:26:20

invalid speed keyframe 54 frame 56 speed 3.110815121285476
 [[ 0.99943481  0.03352527  0.00247374 -1.15880609]
 [-0.03350418  0.99940556 -0.00812421  0.17873761]
 [-0.00274464  0.00803674  0.99996394  1.68964362]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 55
get_world_pose  55 [[ -1.57958792e-01   8.35889205e-02  -9.83901373e-01   2.82205336e+01]
 [ -6.11250304e-03   9.96308743e-01   8.56243300e-02  -5.90537000e-01]
 [  9.87426786e-01   1.95392158e-02  -1.56864787e-01  -2.57453945e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (57 of 1101) |#                      | Elapsed Time: 0:09:42 ETA:  8:50:36

invalid speed keyframe 55 frame 57 speed 13.122645864274848
 [[  9.97626116e-01   6.59990684e-02  -1.96534110e-02   3.81722275e+00]
 [ -6.59656944e-02   9.97819142e-01   2.34230938e-03  -5.84468810e-02]
 [  1.97651399e-02  -1.04029810e-03   9.99804109e-01   1.30910545e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 56
get_world_pose  56 [[ -1.63882234e-01   8.51708292e-02  -9.82796288e-01   2.68576654e+01]
 [ -9.66708595e-03   9.96079397e-01   8.79339624e-02  -6.55994860e-01]
 [  9.86432542e-01   2.39115904e-02  -1.62416363e-01  -2.62931318e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (59 of 1101) |#                      | Elapsed Time: 0:10:29 ETA:  9:12:53

invalid speed keyframe 56 frame 59 speed 4.936194194660805
 [[  9.99846586e-01   5.90585306e-03   1.64901797e-02  -3.71040024e+00]
 [ -5.88869131e-03   9.99982068e-01  -1.08908804e-03  -6.04206184e-01]
 [ -1.64963160e-02   9.91815377e-04   9.99863435e-01   2.17624438e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 58
get_world_pose  58 [[ -1.27982740e-01   7.03769262e-02  -9.89276254e-01   3.10166040e+01]
 [ -1.80700127e-02   9.97148084e-01   7.32746456e-02   2.30323898e+00]
 [  9.91611765e-01   2.72541244e-02  -1.26346032e-01  -3.35904374e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (60 of 1101) |#                      | Elapsed Time: 0:11:06 ETA:  9:26:14

invalid speed keyframe 58 frame 60 speed 0.41333252042113355
 [[ 0.99994272  0.00405039 -0.009907    1.61643706]
 [-0.00402762  0.9999892   0.0023174  -0.41542308]
 [ 0.00991628 -0.00227736  0.99994824 -1.08269707]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 59
get_world_pose  59 [[ -1.12923733e-01   6.32848900e-02  -9.91586231e-01   2.85440003e+01]
 [ -1.09239656e-02   9.97830194e-01   6.49274334e-02   1.07764287e+00]
 [  9.93543606e-01   1.81639021e-02  -1.11987389e-01  -3.45184061e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (61 of 1101) |#                      | Elapsed Time: 0:11:43 ETA:  9:37:42

invalid speed keyframe 59 frame 61 speed 6.3803454908391615
 [[ 0.99254548  0.10705774  0.05824177 -2.70113353]
 [-0.10792777  0.99408638  0.01199451  0.02266915]
 [-0.05661324 -0.018191    0.99823045  4.83420588]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 60
get_world_pose  60 [[ -1.11813600e-01   6.44275997e-02  -9.91638444e-01   2.97088458e+01]
 [ -1.21938415e-02   9.97731967e-01   6.61984350e-02   1.04005828e+00]
 [  9.93654381e-01   1.94937674e-02  -1.10774383e-01  -3.45733016e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (64 of 1101) |#                      | Elapsed Time: 0:12:31 ETA:  8:05:49

invalid speed keyframe 60 frame 64 speed 1.9596619960723274
 [[  9.99945406e-01  -6.65910098e-03  -8.05243885e-03   1.51630983e+00]
 [  6.65004112e-03   9.99977225e-01  -1.15136009e-03  -1.09527707e-01]
 [  8.05992248e-03   1.09774819e-03   9.99966916e-01  -4.09075478e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 63
get_world_pose  63 [[ -1.08803117e-01   5.95835357e-02  -9.92276012e-01   3.43569663e+01]
 [ -2.25380040e-02   9.97797563e-01   6.23863835e-02   1.05013226e+00]
 [  9.93807788e-01   2.91517537e-02  -1.07220592e-01  -3.37974424e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (65 of 1101) |#                      | Elapsed Time: 0:13:05 ETA:  8:00:13

set_previous_keyframe 64
get_world_pose  64 [[ -1.07181224e-01   6.00409289e-02  -9.92424945e-01   3.59267060e+01]
 [ -2.26523703e-02   9.97768357e-01   6.28106418e-02   9.62758494e-01]
 [  9.93981416e-01   2.92128988e-02  -1.05581964e-01  -3.36412044e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (66 of 1101) |#                      | Elapsed Time: 0:13:39 ETA:  7:55:33

invalid speed keyframe 64 frame 66 speed 5.5728465269736915
 [[ 0.99814538  0.02013502  0.0574489  -2.70474733]
 [-0.01983395  0.99978643 -0.00580597  0.55613633]
 [-0.05755353  0.00465577  0.99833157  4.02147714]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 65
get_world_pose  65 [[ -9.57826753e-02   5.81293151e-02  -9.93703508e-01   3.56107812e+01]
 [ -3.38872314e-02   9.97524300e-01   6.16191988e-02   1.24689324e+00]
 [  9.94825278e-01   3.95759124e-02  -9.35757046e-02  -3.49948877e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (67 of 1101) |#                      | Elapsed Time: 0:14:15 ETA:  7:50:10

invalid speed keyframe 65 frame 67 speed 0.6012873157380418
 [[ 0.99996987 -0.00631069 -0.00452018  0.7858452 ]
 [ 0.00629725  0.99997573 -0.00298091 -0.07195508]
 [ 0.00453888  0.00295236  0.99998534 -1.04232509]
 [ 0.          0.          0.          1.        ]]
set_previous_keyframe 66
get_world_pose  66 [[ -9.16448428e-02   5.70769001e-02  -9.94154641e-01   3.65885709e+01]
 [ -3.39595776e-02   9.97596102e-01   6.04050021e-02   1.44700457e+00]
 [  9.95212525e-01   3.92968786e-02  -8.94862305e-02  -3.53095570e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (68 of 1101) |#                      | Elapsed Time: 0:14:50 ETA:  7:44:14

set_previous_keyframe 67
get_world_pose  67 [[ -0.08494555   0.05563144  -0.99483134  36.90909921]
 [ -0.03778806   0.99754194   0.05900962   1.41523574]
 [  0.99566878   0.04260535  -0.08263454 -36.27433885]
 [  0.           0.           0.           1.        ]]


  6% (69 of 1101) |#                      | Elapsed Time: 0:15:26 ETA:  8:30:08

set_previous_keyframe 68
get_world_pose  68 [[ -0.07726086   0.05419467  -0.99553689  36.82077306]
 [ -0.0442946    0.99734905   0.0577309    1.61089626]
 [  0.99602648   0.04855724  -0.07465551 -37.33016574]
 [  0.           0.           0.           1.        ]]


  6% (70 of 1101) |#                      | Elapsed Time: 0:16:02 ETA:  8:29:17

set_previous_keyframe 69
get_world_pose  69 [[ -0.06902991   0.04869872  -0.99642526  37.63646746]
 [ -0.06582353   0.99640898   0.05325802   1.98860631]
 [  0.99544067   0.06926462  -0.0655765  -37.32342967]
 [  0.           0.           0.           1.        ]]


  6% (72 of 1101) |#                      | Elapsed Time: 0:16:48 ETA:  7:44:43

invalid speed keyframe 69 frame 72 speed 25.190876993055088
 [[  9.96797611e-01  -2.64638219e-03  -7.99219564e-02   1.01784675e+01]
 [ -2.59861257e-03   9.97852386e-01  -6.54512205e-02   5.50740792e+00]
 [  7.99235238e-02   6.54493064e-02   9.94649998e-01   2.17152253e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 71
get_world_pose  71 [[ -4.68543397e-02   1.41006355e-02  -9.98802204e-01   3.83056854e+01]
 [ -3.93843359e-02   9.99096791e-01   1.59523343e-02   6.71762099e+00]
 [  9.98125015e-01   4.00845976e-02  -4.62566763e-02  -4.02157926e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (74 of 1101) |#                      | Elapsed Time: 0:17:36 ETA:  8:40:38

invalid speed keyframe 71 frame 74 speed 0.2630475981328573
 [[  9.99728557e-01  -2.16178819e-02  -8.68790498e-03   7.94182212e-01]
 [  2.08818371e-02   9.96783735e-01  -7.73701119e-02   1.01325597e+01]
 [  1.03325403e-02   7.71676909e-02   9.96964586e-01  -4.03306951e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 73
get_world_pose  73 [[ -4.35536243e-02  -4.77087967e-02  -9.97911295e-01   4.17383787e+01]
 [ -1.51675817e-03   9.98861128e-01  -4.76880084e-02   1.37993519e+01]
 [  9.99049939e-01  -5.63395493e-04  -4.35763850e-02  -4.11202937e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (76 of 1101) |#                      | Elapsed Time: 0:18:24 ETA:  8:06:19

set_previous_keyframe 75
get_world_pose  75 [[ -4.08153181e-02  -1.18108549e-01  -9.92161519e-01   4.27684059e+01]
 [ -1.84492427e-02   9.92908764e-01  -1.17438542e-01   1.60275663e+01]
 [  9.98996364e-01   1.35113372e-02  -4.27049004e-02  -4.16979739e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (77 of 1101) |#                      | Elapsed Time: 0:19:04 ETA:  8:13:27

invalid speed keyframe 75 frame 77 speed 17.74350357547339
 [[  9.96588704e-01  -1.83401276e-02  -8.04648651e-02   9.80894998e+00]
 [  1.55868166e-02   9.99275757e-01  -3.47132819e-02   2.00232763e+00]
 [  8.10432350e-02   3.33406735e-02   9.96152796e-01   1.58963133e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
set_previous_keyframe 76
get_world_pose  76 [[ -2.91173895e-02  -1.13267076e-01  -9.93137829e-01   4.22623838e+01]
 [ -1.38477335e-02   9.93509460e-01  -1.12903465e-01   1.53596044e+01]
 [  9.99480074e-01   1.04652539e-02  -3.04968942e-02  -4.34052101e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  7% (78 of 1101) |#                      | Elapsed Time: 0:19:40 ETA:  8:13:42

In [ ]:
import shutil
OUTDIR = 'results'
try:
    shutil.rmtree(OUTDIR)
except:
    pass
os.mkdir(OUTDIR)
keyframes_np = keyframes_to_np(seq.keyframes)
mappoints = get_mappoints(seq.keyframes)
mappoints_np = mappoints_to_np(mappoints)
links_np = links_to_np(mappoints)
suffix = '_{}_{}_{}_{}'.format(FRAMECOUNT, PATCH_SIZE, STEREO_CONFIDENCE, SEQUENCE_CONFIDENCE)
np.save(OUTDIR + '/mappoints' + suffix, mappoints_np)
np.save(OUTDIR + '/links' + suffix, links_np)
np.save(OUTDIR + '/keyframes' + suffix, keyframes_np)